security:
    encoders:
        # use your user class name here
        App\Entity\Utilisateur:
            # bcrypt or argon2i are recommended
            # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: argon2i
            cost: 12

    providers:
        in_memory:
            entity:
                class: App\Entity\Utilisateur
                # the property to query by - e.g. username, email, etc
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            guard:
                authenticators:
                - App\Security\LoginFormAuthenticator

            pattern: ^/

            logout:
                path: app_logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
      - { path: ^/administration/, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
